### PR TITLE
Update Imgfilter documentation

### PR DESCRIPTION
**Pull request by Keanna-K**
- Fixed inconsistent naming of imgfilter function
- updated imgfilter documentation and examples 
- minor spelling fixes in the vignette

### CODE REVIEW

**Comment by zoepan00** [comment]
@Keanna-K  Please check why check is not passed.

**Review by clsu22 — CHANGES_REQUESTED** [review]
seems didn't pass R check. please fix

**Comment by Keanna-K** [comment]
> @Keanna-K Please check why check is not passed.

Seems like my merge conflict updates were not pushed. I have fixed that now!

**Review by zoepan00 — APPROVED** [review]
Looks good

**Review by clsu22 — APPROVED** [review]

**Pull request merged**
